#pragma once

enum AnimationExtrapolate {
	EXTRAPOLATE_CONSTANT,
	EXTRAPOLATE_LINEAR,
	EXTRAPOLATE_CYCLE,
	EXTRAPOLATE_CYCLE_OFFSET,
	EXTRAPOLATE_BOUNCE,
};
enum AnimationTangent {
	ANIMATION_TANGENT_MANUAL,
	ANIMATION_TANGENT_FLAT,
	ANIMATION_TANGENT_LINEAR,
	ANIMATION_TANGENT_SMOOTH,
	ANIMATION_TANGENT_STEP,
};

enum ClearFlags {
	CLEAR_NONE = 0,
	CLEAR_DEPTH = 1,
	CLEAR_COLOR = 2,
	CLEAR_COLOR_DEPTH = 3,
	CLEAR_SKYBOX = 7
};

enum CommandBufferState {
	CMDBUF_STATE_RECORDING,
	CMDBUF_STATE_PENDING,
	CMDBUF_STATE_DONE
};

enum ConsoleColor {
	COLOR_RED,
	COLOR_GREEN,
	COLOR_BLUE,
	COLOR_YELLOW,
	COLOR_CYAN,
	COLOR_MAGENTA,

	COLOR_RED_BOLD,
	COLOR_GREEN_BOLD,
	COLOR_BLUE_BOLD,
	COLOR_YELLOW_BOLD,
	COLOR_CYAN_BOLD,
	COLOR_MAGENTA_BOLD
};

enum LayoutAxis {
	LAYOUT_HORIZONTAL = 0,
	LAYOUT_VERTICAL = 1
};

enum StereoEye {
	EYE_NONE = 0,
	EYE_LEFT = 0,
	EYE_RIGHT = 1
};

enum StereoMode {
	STEREO_NONE = 0,
	STEREO_SBS_VERTICAL = 1,
	STEREO_SBS_HORIZONTAL = 2
};

enum TextAnchor {
	TEXT_ANCHOR_MIN, TEXT_ANCHOR_MID, TEXT_ANCHOR_MAX
};

enum TextureLoadFlags {
	TEXTURE_LOAD_SRGB,
	TEXTURE_LOAD_SIGNED
};